# Generated by Django 6.0.6 on 2026-06-22 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_betanalysis_created_at_betanalysis_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('game_type', models.CharField(max_length=50)),
                ('number_of_games', models.IntegerField(blank=True, max_length=3, null=True)),
                ('result', models.CharField(blank=True, choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BetAnalysis',
        ),
    ]
